### ISSUE TITLE
API

### ISSUE THREAD

**Issue by eratel** [SinMu-L/chatweb#1]

**Comment by eratel** [comment]
API KEY在哪里替换，没找到为止

**Comment by SinMu-L** [comment]
本地运行的话，新建一个`.env` 文件，填充内容如下
```
VITE_AI_KEY =xxxx

VITE_AI_BASE_URL =xxxx
```
![image](https://github.com/SinMu-L/chatweb/assets/39164106/f8b2ce93-67bc-459c-85f1-a45b39f880c5)


部署到Vercel上的话，就新建环境变量就好
![image](https://github.com/SinMu-L/chatweb/assets/39164106/8fbad19f-38c2-4524-b2d2-c8b738e21c7b)

**Comment by SinMu-L** [comment]
不过目前master分支用不了。等我这个月有空我更新一个版本吧

**Comment by SinMu-L** [comment]
已退回到原来的版本，在`.env` 文件中修改就行
